/*
 * @Author       : jry
 * @Description  :
 * @version      : 4.0
 * @Date         : 2025-11-18 09:30:08
 * @LastAuthor   : jry
 * @lastTime     : 2025-11-18 09:30:08
 * @FilePath     : /uview-plus/uni_modules/uv-plus/components/up-dropdown-item/dropdown-item.uts
 */
export default {
    // dropdown-item组件
    dropdownItem: {
        // #ifdef VUE3
        modelValue: '',
        // #endif
        // #ifdef VUE2
        value: '',
        // #endif
        title: '',
        options: [] as UTSJSONObject[],
        disabled: false,
        height: 'auto',
        closeOnClickOverlay: true
    }
} as UTSJSONObject