/*
 * @Author       : LQ
 * @Description  :
 * @version      : 3.0
 * @Date         : 2021-08-20 16:44:21
 * @LastAuthor   : jry
 * @lastTime     : 2025-12-22 00:10:00
 * @FilePath     : /uview-plus/libs/config/props/tabbar.uts
 */
export default {
    // tabbar
    tabbar: {
        value: null as string | number | null,
        safeAreaInsetBottom: true,
        border: true,
        zIndex: 1,
        activeColor: '#1989fa',
        inactiveColor: '#7d7e80',
        fixed: true,
        placeholder: true,
        borderColor: '',
        backgroundColor: ''
    }
} as UTSJSONObject