'use strict'

interface InterceptorHandler {
    fulfilled: ((config: any) => any) | null
    rejected: ((config: any) => any) | null
}

export default class InterceptorManager {
    handlers: InterceptorHandler[]

    constructor() {
        this.handlers = []
    }

    /**
     * Add a new interceptor to the stack
     *
     * @param {Function} fulfilled The function to handle `then` for a `Promise`
     * @param {Function} rejected The function to handle `reject` for a `Promise`
     *
     * @return {Number} An ID used to remove interceptor later
     */
    use(fulfilled: (config: any) => any, rejected?: (config: any) => any): number {
        this.handlers.push({
            fulfilled,
            rejected: rejected || null
        })
        return this.handlers.length - 1
    }

    /**
     * Remove an interceptor from the stack
     *
     * @param {Number} id The ID that was returned by `use`
     */
    eject(id: number): void {
        if (this.handlers[id]) {
            this.handlers[id] = {
                fulfilled: null,
                rejected: null
            }
        }
    }

    /**
     * Iterate over all the registered interceptors
     *
     * This method is particularly useful for skipping over any
     * interceptors that may have become `null` calling `eject`.
     *
     * @param {Function} fn The function to call for each interceptor
     */
    forEach(fn: (h: InterceptorHandler) => void): void {
        this.handlers.forEach((h: InterceptorHandler) => {
            if (h.fulfilled !== null) {
                fn(h)
            }
        })
    }
}
