'use strict'

import { forEach, isArray, isDate, isObject } from '../utils'

function encode(val: string): string {
    return encodeURIComponent(val)!
        .replace(/%40/gi, '@')
        .replace(/%3A/gi, ':')
        .replace(/%24/g, '$')
        .replace(/%2C/gi, ',')
        .replace(/%20/g, '+')
        .replace(/%5B/gi, '[')
        .replace(/%5D/gi, ']')
}

/**
 * 将 params 拼接到 url（uts 版）
 * @param url 基础 url
 * @param params 查询参数（UTSJSONObject / 数组 / 基本类型）
 */
export default function buildURL(url: string, params: any | null = null): string {
    if (params == null) {
        return url
    }

    const parts: string[] = []

    forEach(params, (val: any | null, key: any, obj: any | null) => {
        if (val == null) {
            return
        }
        let keyStr: string = key.toString()
        let values: any = val
        if (isArray(val)) {
            keyStr = `${keyStr}[]`
        } else {
            values = [val]
        }
        forEach(values, (v: any | null, k2: any, o2: any | null) => {
            let vv: any | null = v
            if (vv == null) {
                return
            }
            if (isDate(vv)) {
                vv = (vv as Date).toISOString()
            } else if (isObject(vv)) {
                vv = JSON.stringify(vv)
            }
            parts.push(`${encode(keyStr)}=${encode(`${vv}`)}`)
        })
    })

    let out: string = url
    const serializedParams: string = parts.join('&')
    if (serializedParams.length > 0) {
        const hashmarkIndex = out.indexOf('#')
        if (hashmarkIndex !== -1) {
            out = out.slice(0, hashmarkIndex)
        }
        out += (out.indexOf('?') === -1 ? '?' : '&') + serializedParams
    }

    return out
}
